{% set name = "sbpy" %}
{% set version = "0.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b88a53688a26bc2b572e1f4543fdae4fe2f4fe6c305085432dcc7ff614c6cb7

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.0
    - astropy-base >=5.3.3
    - ads >=0.12
    - synphot >=1.1.1
    - astroquery >=0.4.5
    - scipy >=1.10
    - photutils-base
    - pyyaml
    - ginga

test:
  requires:
    - python {{ python_min }}
  imports:
    - sbpy
    - sbpy.units
    - sbpy.obsutil
    - sbpy.photometry

about:
  home: https://sbpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: sbpy is a Python package for small-body planetary astronomy.
  description: |
    sbpy is a community effort to build a Python package for small-body
    planetary astronomy in the form of an Astropy affiliated package. The
    goal is to collect and implement well-tested and well-documented code
    for the scientific study of asteroids and comets, including (but not
    limited to) observation planning, photometric models, spectroscopic
    analysis, asteroid thermal models, lightcurve and shape tools, and
    access tools for relevant databases.
  doc_url: https://sbpy.readthedocs.io/
  dev_url: https://github.com/NASA-Planetary-Science/sbpy

extra:
  recipe-maintainers:
    - bsipocz
    - mwcraig
